---
- hosts: sandbox
  become: true
  vars:
    ansible_path: /home/csubbrayalu/ansible
  roles:
    - setup
    - add-repos
    - yum-pkg
    - yum-util-pkg
    - yum-acc-pkg
    - yum-editor-pkg
    - terraform
#    - python3
