---
- name: Download terraform archive Linux 64 bits
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "{{ ansible_path }}/tmp/terraform-{{terraform_version}}.zip"
