---
- name: Check terraform version
  shell: "terraform --version 2>&1 | grep {{terraform_version}}"
  failed_when: false
  changed_when: false
  register: terraform_versions_match

- include_tasks: download.yml
  when: terraform_versions_match.rc != 0

- name: Unarchive Terraform archive
  unarchive:
    src: "{{ ansible_path }}/tmp/terraform-{{terraform_version}}.zip"
    dest: /usr/local/bin
    copy: no
  when: terraform_versions_match.rc != 0 or terraform_directory | changed
